### ISSUE TITLE
Compliation error - return value 

### ISSUE THREAD

**Issue by bkmgit** [deadmorous/ode_num_int#2]
When trying to compile get the following errors:

[ 75%] Building CXX object src/CMakeFiles/ode_num_int.dir/test_vector_mapping.cpp.o
In file included from /home/ODE_int/ode_num_int/include/ode_num_int/VectorNarrowingMapping.h:1:0,
                 from /home/ODE_int/ode_num_int/src/test_vector_mapping.cpp:3:
/home/ODE_int/ode_num_int/include/ode_num_int/./alg/VectorNarrowingMapping.h: In member function ‘void ctm::math::VectorNarrowingMapping<VD>::disabledOutputIndices() const’:
/home/ODE_int/ode_num_int/include/ode_num_int/./alg/VectorNarrowingMapping.h:37:20: error: return-statement with a value, in function returning 'void' [-fpermissive]
             return m_disabledOutputIndices;
                    ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ode_num_int.dir/build.make:327: src/CMakeFiles/ode_num_int.dir/test_vector_mapping.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: src/CMakeFiles/ode_num_int.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Should the function disabledOutputIndices() be of type V rather than of type void?

**Comment by deadmorous** [comment]
Oops... This means I need to try compiling with gcc again. VC++ sometimes doesn't see some obvious bugs in templates. I fixed this issue, but guess there might be others. Will try building with gcc tomorrow.

**Comment by deadmorous** [comment]
Which compiler did you use? gcc 5.4.0 doesn't notice wrong return type, unless the method gets actually called. Did recent fix (commit 21ec829d3ba94f3b16f4509e38b6ff3978af7587) help? If so, I will close the issue.
